name: Kubebuilder custom controller CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install KinD
      run: make kind-install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Unit tests
      run: make test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Create KinD Cluster -> Build Docker image -> Load image into KinD -> Helm install custom controller
      run: make deploy

    - name: Apply test deployment
      run: make apply-test-deployment

    - name: Cleanup
      if: always()
      run: make destroy
